CREATE TABLE IF NOT EXISTS orders (
    id            UUID         PRIMARY KEY,
    user_id       VARCHAR(255),
    payment_id    VARCHAR(255),
    status        VARCHAR(50),
    total_amount  NUMERIC(19, 2)
);

CREATE TABLE IF NOT EXISTS order_items (
    id          UUID         PRIMARY KEY,
    product_id  VARCHAR(255),
    quantity    INT,
    price       NUMERIC(19, 2)
);

-- Join table generated by Hibernate @OneToMany without @JoinColumn
CREATE TABLE IF NOT EXISTS orders_items (
    order_id  UUID REFERENCES orders(id),
    items_id  UUID REFERENCES order_items(id),
    PRIMARY KEY (order_id, items_id)
);

CREATE TABLE IF NOT EXISTS outbox (
    id             UUID         PRIMARY KEY,
    aggregate_type VARCHAR(255),
    aggregate_id   VARCHAR(255),
    event_type     VARCHAR(255),
    payload        TEXT,
    created_at     TIMESTAMPTZ,
    published      BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox (created_at) WHERE published = FALSE;
